!
! FRR configuration for a2 (Simplified)
!
frr version 8.1
frr defaults traditional
hostname a2
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:a2::1/128
 ipv6 router isis SRv6
!
# -------------
# interface <interface_name>中需修改为容器内对应网口名
# ! 修改完后需要删除该部分注释（删除 # 以及 # 后的内容）
# -------------
interface veth-a2-a1
 ipv6 address fc00:12::2/64
 ipv6 router isis SRv6
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
# -------------
# interface <interface_name>中需修改为容器内对应网口名
# ! 修改完后需要删除该部分注释（删除 # 以及 # 后的内容）
# -------------
interface veth-a2-a3
 ipv6 address fc00:23::1/64
 ipv6 router isis SRv6
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface veth-a2-a5
 ipv6 address fc00:25::1/64
 ipv6 router isis SRv6
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
!
router isis SRv6
 net 49.0000.0000.0002.00
 is-type level-2-only
 topology ipv6-unicast
 log-adjacency-changes
!
line vty
!
end
