!
! FRR configuration for r38n14
! IS-IS area: 3  is-type: level-1
!
frr version 9.1
frr defaults traditional
hostname r38n14
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:0026:000e::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r38n14-r38n13
 ipv6 address fc00:0026:000d:000e::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r38n14-r38n15
 ipv6 address fc00:0026:000e:000f::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r38n14-r37n14
 ipv6 address fc00:9000:0025:000e::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r38n14-r39n14
 ipv6 address fc00:9000:0026:000e::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SRv6
 net 49.0003.0000.0026.000e.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
