!
! FRR configuration for r3n18
! IS-IS area: 1  is-type: level-1
!
frr version 9.1
frr defaults traditional
hostname r3n18
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:0003:0012::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r3n18-r3n17
 ipv6 address fc00:0003:0011:0012::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r3n18-r3n19
 ipv6 address fc00:0003:0012:0013::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r3n18-r2n18
 ipv6 address fc00:9000:0002:0012::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r3n18-r4n18
 ipv6 address fc00:9000:0003:0012::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SRv6
 net 49.0001.0000.0003.0012.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
