!
! FRR configuration for r14n1
! IS-IS area: 1  is-type: level-1  role: area
!
frr version 10.5.1
frr defaults traditional
hostname r14n1
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:000e:0001::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r14n1-r14n0
 ipv6 address fc00:000e:0000:0001::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r14n1-r14n2
 ipv6 address fc00:000e:0001:0002::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r14n1-r13n1
 ipv6 address fc00:9000:000d:0001::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r14n1-r15n1
 ipv6 address fc00:9000:000e:0001::1/64
!
router isis SRv6
 net 49.0001.0000.000e.0001.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
