!
! FRR configuration for r20n13
! IS-IS area: 2  is-type: level-1
!
frr version 9.1
frr defaults traditional
hostname r20n13
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:0014:000d::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r20n13-r20n12
 ipv6 address fc00:0014:000c:000d::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r20n13-r20n14
 ipv6 address fc00:0014:000d:000e::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r20n13-r19n13
 ipv6 address fc00:9000:0013:000d::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r20n13-r21n13
 ipv6 address fc00:9000:0014:000d::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SRv6
 net 49.0002.0000.0014.000d.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
