!
! FRR configuration for r27n1
! IS-IS area: 2  is-type: level-1  role: area
!
frr version 10.5.1
frr defaults traditional
hostname r27n1
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:001b:0001::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r27n1-r27n0
 ipv6 address fc00:001b:0000:0001::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r27n1-r27n2
 ipv6 address fc00:001b:0001:0002::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r27n1-r26n1
 ipv6 address fc00:9000:001a:0001::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r27n1-r28n1
 ipv6 address fc00:9000:001b:0001::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SRv6
 net 49.0002.0000.001b.0001.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
