!
! FRR configuration for r55n8
! IS-IS area: 4  is-type: level-1
!
frr version 9.1
frr defaults traditional
hostname r55n8
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:0037:0008::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r55n8-r55n7
 ipv6 address fc00:0037:0007:0008::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r55n8-r55n9
 ipv6 address fc00:0037:0008:0009::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r55n8-r54n8
 ipv6 address fc00:9000:0036:0008::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r55n8-r56n8
 ipv6 address fc00:9000:0037:0008::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SRv6
 net 49.0004.0000.0037.0008.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
