!
! FRR configuration for r45n16
! IS-IS area: 4  is-type: level-1-2
!
frr version 9.1
frr defaults traditional
hostname r45n16
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:002d:0010::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r45n16-r45n15
 ipv6 address fc00:002d:000f:0010::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r45n16-r45n17
 ipv6 address fc00:002d:0010:0011::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r45n16-r44n16
 ipv6 address fc00:9000:002c:0010::2/64
 ipv6 router isis SRv6
 isis circuit-type level-2-only
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r45n16-r46n16
 ipv6 address fc00:9000:002d:0010::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
ipv6 route fc00:2d::/43 Null0 table 2004
ipv6 route fc00:2e::/43 Null0 table 2004
ipv6 route fc00:2f::/43 Null0 table 2004
ipv6 route fc00:30::/43 Null0 table 2004
ipv6 route fc00:31::/43 Null0 table 2004
ipv6 route fc00:32::/43 Null0 table 2004
ipv6 route fc00:33::/43 Null0 table 2004
ipv6 route fc00:34::/43 Null0 table 2004
ipv6 route fc00:35::/43 Null0 table 2004
ipv6 route fc00:36::/43 Null0 table 2004
ipv6 route fc00:37::/43 Null0 table 2004
ipv6 route fc00:38::/43 Null0 table 2004
ipv6 route fc00:39::/43 Null0 table 2004
ipv6 route fc00:3a::/43 Null0 table 2004
ipv6 route fc00:3b::/43 Null0 table 2004
!
router isis SRv6
 net 49.0004.0000.002d.0010.00
 is-type level-1-2
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 attached-bit send
 redistribute ipv6 table 2004 level-2
 log-adjacency-changes
!
line vty
!
end
