!
! FRR configuration for r40n0
! IS-IS area: 3  is-type: level-1
!
frr version 9.1
frr defaults traditional
hostname r40n0
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:0028:0000::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r40n0-r40n1
 ipv6 address fc00:0028:0000:0001::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r40n0-r40n19
 ipv6 address fc00:0028:0013:0000::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r40n0-r39n0
 ipv6 address fc00:9000:0027:0000::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r40n0-r41n0
 ipv6 address fc00:9000:0028:0000::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SRv6
 net 49.0003.0000.0028.0000.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
