!
! FRR configuration for r15n6
! IS-IS area: 2  is-type: level-1-2
!
frr version 9.1
frr defaults traditional
hostname r15n6
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:000f:0006::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r15n6-r15n5
 ipv6 address fc00:000f:0005:0006::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r15n6-r15n7
 ipv6 address fc00:000f:0006:0007::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r15n6-r14n6
 ipv6 address fc00:9000:000e:0006::2/64
 ipv6 router isis SRv6
 isis circuit-type level-2-only
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r15n6-r16n6
 ipv6 address fc00:9000:000f:0006::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
ipv6 route fc00:f::/43 Null0 table 2002
ipv6 route fc00:10::/43 Null0 table 2002
ipv6 route fc00:11::/43 Null0 table 2002
ipv6 route fc00:12::/43 Null0 table 2002
ipv6 route fc00:13::/43 Null0 table 2002
ipv6 route fc00:14::/43 Null0 table 2002
ipv6 route fc00:15::/43 Null0 table 2002
ipv6 route fc00:16::/43 Null0 table 2002
ipv6 route fc00:17::/43 Null0 table 2002
ipv6 route fc00:18::/43 Null0 table 2002
ipv6 route fc00:19::/43 Null0 table 2002
ipv6 route fc00:1a::/43 Null0 table 2002
ipv6 route fc00:1b::/43 Null0 table 2002
ipv6 route fc00:1c::/43 Null0 table 2002
ipv6 route fc00:1d::/43 Null0 table 2002
!
router isis SRv6
 net 49.0002.0000.000f.0006.00
 is-type level-1-2
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 attached-bit send
 redistribute ipv6 table 2002 level-2
 log-adjacency-changes
!
line vty
!
end
