!
! FRR configuration for r58n5
! IS-IS area: 4  is-type: level-1  role: area
!
frr version 10.5.1
frr defaults traditional
hostname r58n5
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:003a:0005::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r58n5-r58n4
 ipv6 address fc00:003a:0004:0005::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r58n5-r58n6
 ipv6 address fc00:003a:0005:0006::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r58n5-r57n5
 ipv6 address fc00:9000:0039:0005::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r58n5-r59n5
 ipv6 address fc00:9000:003a:0005::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SRv6
 net 49.0004.0000.003a.0005.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
