!
! FRR configuration for r41n5
! IS-IS area: 3  is-type: level-1
!
frr version 9.1
frr defaults traditional
hostname r41n5
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:0029:0005::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r41n5-r41n4
 ipv6 address fc00:0029:0004:0005::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r41n5-r41n6
 ipv6 address fc00:0029:0005:0006::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r41n5-r40n5
 ipv6 address fc00:9000:0028:0005::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r41n5-r42n5
 ipv6 address fc00:9000:0029:0005::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SRv6
 net 49.0003.0000.0029.0005.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
