!
! FRR configuration for r46n10
! IS-IS area: 4  is-type: level-1
!
frr version 9.1
frr defaults traditional
hostname r46n10
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:002e:000a::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r46n10-r46n9
 ipv6 address fc00:002e:0009:000a::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r46n10-r46n11
 ipv6 address fc00:002e:000a:000b::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r46n10-r45n10
 ipv6 address fc00:9000:002d:000a::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r46n10-r47n10
 ipv6 address fc00:9000:002e:000a::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SRv6
 net 49.0004.0000.002e.000a.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
