!
! FRR configuration for r52n18
! IS-IS area: 4  is-type: level-1
!
frr version 9.1
frr defaults traditional
hostname r52n18
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:0034:0012::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r52n18-r52n17
 ipv6 address fc00:0034:0011:0012::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r52n18-r52n19
 ipv6 address fc00:0034:0012:0013::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r52n18-r51n18
 ipv6 address fc00:9000:0033:0012::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r52n18-r53n18
 ipv6 address fc00:9000:0034:0012::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SRv6
 net 49.0004.0000.0034.0012.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
