!
! FRR configuration for r44n14
! IS-IS area: 3  is-type: level-1-2
!
frr version 9.1
frr defaults traditional
hostname r44n14
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:002c:000e::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r44n14-r44n13
 ipv6 address fc00:002c:000d:000e::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r44n14-r44n15
 ipv6 address fc00:002c:000e:000f::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r44n14-r43n14
 ipv6 address fc00:9000:002b:000e::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r44n14-r45n14
 ipv6 address fc00:9000:002c:000e::1/64
 ipv6 router isis SRv6
 isis circuit-type level-2-only
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
ipv6 route fc00:1e::/43 Null0 table 2003
ipv6 route fc00:1f::/43 Null0 table 2003
ipv6 route fc00:20::/43 Null0 table 2003
ipv6 route fc00:21::/43 Null0 table 2003
ipv6 route fc00:22::/43 Null0 table 2003
ipv6 route fc00:23::/43 Null0 table 2003
ipv6 route fc00:24::/43 Null0 table 2003
ipv6 route fc00:25::/43 Null0 table 2003
ipv6 route fc00:26::/43 Null0 table 2003
ipv6 route fc00:27::/43 Null0 table 2003
ipv6 route fc00:28::/43 Null0 table 2003
ipv6 route fc00:29::/43 Null0 table 2003
ipv6 route fc00:2a::/43 Null0 table 2003
ipv6 route fc00:2b::/43 Null0 table 2003
ipv6 route fc00:2c::/43 Null0 table 2003
!
router isis SRv6
 net 49.0003.0000.002c.000e.00
 is-type level-1-2
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 attached-bit send
 redistribute ipv6 table 2003 level-2
 log-adjacency-changes
!
line vty
!
end
