!
! FRR configuration for r2n9
! IS-IS area: 1  is-type: level-1  role: area
!
frr version 10.5.1
frr defaults traditional
hostname r2n9
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:0002:0009::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r2n9-r2n8
 ipv6 address fc00:0002:0008:0009::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r2n9-r2n10
 ipv6 address fc00:0002:0009:000a::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r2n9-r1n9
 ipv6 address fc00:9000:0001:0009::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r2n9-r3n9
 ipv6 address fc00:9000:0002:0009::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SRv6
 net 49.0001.0000.0002.0009.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
