!
! FRR configuration for r57n12
! IS-IS area: 4  is-type: level-1
!
frr version 9.1
frr defaults traditional
hostname r57n12
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:0039:000c::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r57n12-r57n11
 ipv6 address fc00:0039:000b:000c::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r57n12-r57n13
 ipv6 address fc00:0039:000c:000d::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r57n12-r56n12
 ipv6 address fc00:9000:0038:000c::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r57n12-r58n12
 ipv6 address fc00:9000:0039:000c::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SRv6
 net 49.0004.0000.0039.000c.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
