!
! FRR configuration for r31n14
! IS-IS area: 3  is-type: level-1
!
frr version 9.1
frr defaults traditional
hostname r31n14
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
ipv6 forwarding
!
interface lo
 description SRv6 Locator Interface
 ipv6 address fc00:001f:000e::1/128
 ipv6 router isis SRv6
 isis passive
 isis circuit-type level-1
!
interface r31n14-r31n13
 ipv6 address fc00:001f:000d:000e::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r31n14-r31n15
 ipv6 address fc00:001f:000e:000f::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r31n14-r30n14
 ipv6 address fc00:9000:001e:000e::2/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
interface r31n14-r32n14
 ipv6 address fc00:9000:001f:000e::1/64
 ipv6 router isis SRv6
 isis circuit-type level-1
 isis network point-to-point
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SRv6
 net 49.0003.0000.001f.000e.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 attached-bit receive
 log-adjacency-changes
!
line vty
!
end
